/*=================================================================
 *
 * das3steptest.c
 *
 * This is a MEX function to test the das3step function in das3mex.c
 * it is compiled using MEX because that is the easiest way to link with LAPACK
 * and MEX is used to compile S-functions also.
 *
 * Compilation is set up in the Makefile\
 * Use like this: >> das3steptest
 *
 * The test replicates das3test('simulate'), measures computation speed,
 * and writes the simulated trajectory x(t) on das3steptest.txt
 * The simulated trajectory should be compared to simulation.mat
 * produced by das3test('simulate').  The results should be identical.
 *
 *=================================================================*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include "mex.h"
#include "das3mex.h"
#define WRITEFILE 1
#define NOWRITEFILE 0

// run the fixed-step simulation as specified in das3test('simulate');
void simulate(int nsteps, double h, int writefile) {
	int i,j;
	double x[NSTATES], u[NMUS], exF[2], F_SCAP[2][3], F_GH[3], f[NSTATES];
	int status;
	FILE *fid;

	// =============== initialization ====================

	// put zeros in exF (arm support force input)
	exF[0] = 0.0;
	exF[1] = 0.0;

	// load equilibrium.txt to get the initial condition
	// this file is generated by >> das3test('equilibrium')
	printf("das3steptest: reading initial condition from equilibrium.txt...\n");
	fid = fopen("equilibrium.txt", "r");
	if (fid == NULL) {
		printf("Error opening equilibrium.txt\n");
		return;
	}
	for (i=0; i<NSTATES; i++) fscanf(fid, "%lf", &x[i]);
	fclose(fid);

	// initialize the das3step function
	printf("das3steptest: initializing das3step...\n");
	status = das3step(x, u, 0.0, exF, F_GH, F_SCAP, f);
	if (status != 0) {
		printf("das3steptest: error in initialization of das3step, status=%d\n", status);
		return;
	}
	
	// ============== end of initialization =================
	
	printf("das3steptest: %d steps of %8.4f s (%8.4f s total)...\n", nsteps, h, nsteps*h);
	
	// if requested, create a file to store the simulated trajectory
	if (writefile) { 
		fid = fopen("das3steptest.txt", "w");
		if (fid == NULL) {
			printf("Error opening file das3steptest.txt\n");
			return;
		}
		printf("das3steptest: writing simulation result on das3steptest.txt\n");
		// write initial x to the file
		for (j=0; j<NSTATES; j++) fprintf(fid, "%22.15e ", x[j]);
		fprintf(fid,"\n");
	}
	
	// do the steps
	for (i=0; i<nsteps; i++) {
		double t = i*h;		// current simulation time
		
		// create the control input for this time step (same as in das3test)
		double trampup = 0.2;		// time for the ramp up part of the stim pattern
		double tpassive = 2.0;		// time for muscles to turn off
		for (j=0; j<NMUS; j++) {
			if (t<trampup) 			u[j] = t/trampup;
			else if (t<tpassive) 	u[j] = 1.0;
			else 					u[j] = 0.0;
		}
	
		// ==== update: generate new state x, based on old state x and controls u =========
		// this uses das3step in das3mex.c
		status = das3step(x, u, h, exF, F_GH, F_SCAP, f);	
		if (status != 0) {
			printf("das3steptest: das3step error in time step %d, status=%d\n", i, status);
			return;
		}
		// ==== end of update code =========================================================
		
		// write x to resultfile
		if (writefile) {
			for (j=0; j<NSTATES; j++) fprintf(fid, "%22.15e ", x[j]);
			fprintf(fid,"\n");
		}
	}
	if (writefile) fclose(fid);
	
	return;
}

// =========================================================================
// mexFunction: no inputs or outputs
// =========================================================================
void mexFunction( int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
	int nsteps = 1333;  	// number of time steos
	double h = 0.003;		// time step (s)

	// run a simulation without writing a file, just to measure computation speed
	time_t start = clock();
	simulate(nsteps, h, NOWRITEFILE);
	double time_used = (clock() - start)/(double)CLOCKS_PER_SEC;
	printf("das3steptest: computation time: %8.3f seconds (%8.3f ms per step)\n", time_used, 1000*time_used/nsteps);
	printf("das3steptest: simulation is %5.2f times faster than real time\n", nsteps*h/time_used);
	
	// then run it again, and write results to das3steptest.txt
	simulate(nsteps, h, WRITEFILE);

}
